from django.contrib import admin
from django.urls import include, path
from .views import views

urlpatterns = [
    path('dich-vu-khac/', views.news, name="news"),
    path('quan-ly-co-so/', views.Cart, name="cart"),
    path('chi-tiet-co-so/<hotel_id>', views.detail_hotel, name="detail_hotel"),
    path('quan-ly-co-so-cho-nguoi-quan-li/', views.manage_hotel, name="manage_hotel"),
    path('don-dat-phong/', views.Order, name="order"),
    path('quan-ly-tai-khoan/', views.manage_account, name="manage_account"),
    path('', views.home, name="home"),
    path('cap-nhat-san-pham/', views.updateItem, name="updateItem"),
    path('update_order/', views.updateOrder, name="update_order"),
    path('dang-ky/', views.register, name="register"),
    path('dang-nhap/', views.loginPage, name="login"),
    path('dang-xuat/', views.logoutPage, name="logout"),
    path('chi-tiet/', views.detail, name="detail"),
    path('chi-tiet-tin-tuc/', views.newdetail, name="newdetail"),
    path('trang-ca-nhan/', views.profile, name="profile"),
    path('dat-phong/', views.booking, name="booking"),
    path('dat-phong-thanh-cong/', views.completebooking, name='completebooking'),
    path('cap-nhat-phong/<room_id>', views.updateRoom, name="update_room"),
    path('cap-nhat-don-dat-phong/<order_id>', views.updateTrade, name="update_trade"),
    path('cap-nhat-co-so/<hotel_id>', views.updateHotel, name="update_hotel"),
    path('chinh-sua-thong-tin/<user_id>', views.edit_profile, name="edit_profile"),
    path('doi-mat-khau', views.change_password, name = "change_password"),
    path('them-phong-moi/', views.add_room, name="add_room"),
    path('them-co-so-moi/', views.add_hotel, name="add_hotel"),
    path('them-co-so-moi-cho-tai-khoan/', views.add_hotel_user, name="add_hotel_user"),
    path('them-tai-khoan/', views.add_account, name="add_account"),
    path('xoa-don-hang/<order_id>/', views.delete_order, name='delete_order'),
    path('xoa-co-so/<hotel_id>/', views.delete_hotel, name='delete_hotel'),
    path('xoa-phong/<room_id>/', views.delete_room, name='delete_room'),
    path('xoa-tai-khoan/<user_id>/', views.delete_account, name='delete_account'),
    path('tra-phong/<order_id>/', views.return_room, name='return_room'),
    path('lich-su/', views.historylist, name='historylist'),
    path('thong-ke-phong/', views.listroom, name='listroom'),
    path('xuat-lich-su/', views.export_history, name='export_history'),
    path('xuat-tai-khoan/', views.export_account, name='export_account'),
    path('xuat-danh-sach-phong/', views.export_room, name='export_room'),
    path('xuat-tai-khoan-mat-mau-moi/', views.export_new_password, name='export_new_password'),
    path('xuat-co-so/', views.export_hotel, name='export_hotel'),
    path('tai-vi-du-co-so/', views.generate_example_hotel, name='download_example_hotel'),
    path('tai-vi-du-phong/', views.generate_example_room, name='download_example_room'),
    path('tai-vi-du-tai-khoan/', views.generate_example_account, name='download_example_account'),
    path('tao-tai-khoan-admin/', views.create_superuser, name='create_superuser'),
    path('loi-dang-nhap/', views.error_login, name='error_login'),
    path('dang-nhap-lai/', views.reset_password, name='reset_password'),
]
