# Generated by Django 5.1.4 on 2025-01-04 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('detail', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('amountprice', models.CharField(default='0', max_length=255)),
                ('onSale', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True, null=True)),
                ('imageP', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('location', models.CharField(max_length=255)),
                ('maplocation', models.CharField(default='N/A', max_length=255)),
                ('rate', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('phonecall', models.CharField(default='0', max_length=255)),
                ('categories', models.ManyToManyField(blank=True, to='home.category')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('product_type', models.ManyToManyField(blank=True, to='home.producttype')),
                ('room_types', models.ManyToManyField(blank=True, to='home.roomtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, default='default-image.png', null=True, upload_to='rooms/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.product')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='home.roomtype', to_field='code')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='home.statustype')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateTimeField(auto_now_add=True)),
                ('datebook', models.DateTimeField(null=True)),
                ('complete', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=False)),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('cname', models.CharField(default='N/A', max_length=255)),
                ('phonecall', models.CharField(default='0', max_length=255)),
                ('cccd', models.CharField(default='0', max_length=255)),
                ('method', models.CharField(default='N/A', max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.room')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateTimeField(blank=True, null=True)),
                ('outdateOrder', models.DateTimeField(auto_now_add=True)),
                ('datebook', models.DateTimeField(null=True)),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('cname', models.CharField(default='N/A', max_length=255)),
                ('phonecall', models.CharField(default='0', max_length=255)),
                ('cccd', models.CharField(default='0', max_length=255)),
                ('method', models.CharField(default='N/A', max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.room')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.room')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(default='N/a', max_length=255)),
                ('birthday', models.DateTimeField(null=True)),
                ('phonecall', models.CharField(default='N/a', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('seller', 'Chủ CS lưu trú'), ('customer', 'Khách hàng'), ('admin', 'Người quản lí')], default='customer', max_length=255)),
                ('data_modified', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('base_password', models.TextField(blank=True, null=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='home.userprofile')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
