# Generated by Django 5.1.4 on 2025-01-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-outdateOrder']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-dateOrder']},
        ),
    ]
