# Generated by Django 4.2.15 on 2024-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
