# Generated by Django 5.1.4 on 2024-12-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['product']},
        ),
    ]
