# Generated by Django 4.2.15 on 2024-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_new_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
    ]
