# Generated by Django 5.1.4 on 2024-12-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
