# Generated by Django 4.2.15 on 2024-08-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='name',
        ),
    ]
