# Generated by Django 4.2.15 on 2024-08-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_password_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='_order',
            new_name='Orders',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='_product',
            new_name='Products',
        ),
    ]
