# Generated by Django 4.2.15 on 2024-08-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename__order_cart_orders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Orders',
            new_name='_order',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Products',
            new_name='_product',
        ),
    ]
