# Generated by Django 4.2.15 on 2024-08-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_orders_cart__order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imageP',
        ),
    ]
