# Generated by Django 4.2.15 on 2024-08-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_image_product_imagep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='_order',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='_product',
            new_name='Product',
        ),
    ]
