# Generated by Django 4.2.15 on 2024-08-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename__order_cart_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
