# Generated by Django 4.2.15 on 2024-09-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorie',
            new_name='category',
        ),
    ]
