# Generated by Django 4.2.15 on 2024-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
