# Generated by Django 4.2.15 on 2024-10-27 07:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0021_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='ad',
        ),
    ]
