# Generated by Django 4.2.15 on 2024-10-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_ad_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageP',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
