# Generated by Django 4.2.15 on 2024-10-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_profile_imagep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imageP',
            new_name='profile_image',
        ),
    ]
