# Generated by Django 4.2.15 on 2024-10-27 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0025_rename_imagep_profile_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='UserProfile',
        ),
    ]
