# Generated by Django 4.2.15 on 2024-11-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default='N/A', max_length=255),
        ),
    ]
