# Generated by Django 4.2.15 on 2024-11-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_product_phone_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default='0', max_length=255),
        ),
    ]
