# Generated by Django 4.2.15 on 2024-11-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_product_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='phone',
            new_name='phoneCall',
        ),
    ]
