# Generated by Django 4.2.15 on 2024-11-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_product_price_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phoneCall',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
