# Generated by Django 4.2.15 on 2024-11-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
