# Generated by Django 4.2.15 on 2024-11-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
