# Generated by Django 4.2.15 on 2024-11-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_product_phone_remove_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phonecall',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
