# Generated by Django 4.2.15 on 2024-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_product_phonecall_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='room1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='room2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='room2bed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='room3bed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='roomvip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
