# Generated by Django 4.2.15 on 2024-11-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_product_quantity_product_room1_product_room2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amountprice',
        ),
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price2bed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price3bed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pricevip',
            field=models.IntegerField(null=True),
        ),
    ]
