# Generated by Django 4.2.15 on 2024-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_price_product_amountprice_product_price1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price2',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price2bed',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price3bed',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricevip',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='room1',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='room2',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='room2bed',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='room3bed',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='roomvip',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
