# Generated by Django 4.2.15 on 2024-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_product_price1_alter_product_price2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(default='N/a', max_length=1000),
        ),
    ]
