# Generated by Django 4.2.15 on 2024-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maplocation',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
