# Generated by Django 4.2.15 on 2024-11-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_product_maplocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maplocation',
            field=models.CharField(default='N/a', max_length=255),
        ),
    ]
