# Generated by Django 4.2.15 on 2024-11-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_product_maplocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price2bed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price3bed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pricevip',
        ),
        migrations.RemoveField(
            model_name='product',
            name='room1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='room2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='room2bed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='room3bed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='roomvip',
        ),
        migrations.AlterField(
            model_name='product',
            name='maplocation',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=255)),
                ('price', models.CharField(default='0', max_length=255)),
                ('room_type', models.CharField(choices=[('1bed', '1 Bed Room'), ('2bed', '2 Bed Room'), ('3bed', '3 Bed Room'), ('vip', 'VIP Room')], max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('rating', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order'),
        ),
    ]
