# Generated by Django 4.2.15 on 2024-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_cart_order_remove_product_price1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1', 'Phòng đơn'), ('2', 'Phòng đôi'), ('3', 'Phòng ba'), ('2bed', 'Phòng 2 giường'), ('3bed', 'Phòng 3 giường'), ('vip', 'Phòng VIP')], max_length=10),
        ),
    ]
