# Generated by Django 4.2.15 on 2024-11-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_cart_apartname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='apartname',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
