# Generated by Django 4.2.15 on 2024-11-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_cart_apartname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='apartname',
            new_name='_apartname',
        ),
    ]
