# Generated by Django 4.2.15 on 2024-11-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_rename_apartname_cart__apartname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='_apartname',
            new_name='apartname',
        ),
    ]
