# Generated by Django 4.2.15 on 2024-11-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_rename__apartname_cart_apartname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='apartname',
        ),
    ]
