# Generated by Django 4.2.15 on 2024-11-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_rename_date_cart_date_added_cart_quantity_cart_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='apartname',
        ),
    ]
