# Generated by Django 4.2.15 on 2024-11-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_remove_order_apartname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='caddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='cname',
        ),
    ]
