# Generated by Django 4.2.15 on 2024-11-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_rename_address_order_caddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='caddress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='datebook',
            field=models.DateTimeField(null=True),
        ),
    ]
