# Generated by Django 4.2.15 on 2024-11-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_rename_caddress_order_address_alter_order_datebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_customer',
        ),
    ]
