# Generated by Django 4.2.15 on 2024-11-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_remove_order__customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
