# Generated by Django 4.2.15 on 2024-11-15 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0057_remove_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_room',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dateOrder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='datebook',
        ),
        migrations.RemoveField(
            model_name='order',
            name='outdateOrder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phonecall',
        ),
        migrations.AddField(
            model_name='order',
            name='_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
