# Generated by Django 4.2.15 on 2024-11-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_order__room_order_address_order_cname_order_datebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='dateOrder',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-16 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='outdateOrder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
