# Generated by Django 4.2.15 on 2024-11-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_order_complete_order_dateorder_order_outdateorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='_customer',
            new_name='customer',
        ),
    ]
