# Generated by Django 4.2.15 on 2024-11-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_rename__customer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
