# Generated by Django 4.2.15 on 2024-11-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='_room',
            new_name='room',
        ),
    ]
