# Generated by Django 4.2.15 on 2024-11-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_rename__room_order_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('seller', 'Chủ Khách Sạn'), ('customer', 'Khách Hàng')], max_length=255),
        ),
    ]
