# Generated by Django 4.2.15 on 2024-11-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0066_order_confirm_alter_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateTimeField(blank=True, null=True)),
                ('outdateOrder', models.DateTimeField(auto_now_add=True)),
                ('datebook', models.DateTimeField(null=True)),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('cname', models.CharField(default='N/A', max_length=255)),
                ('phonecall', models.CharField(default='0', max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.room')),
            ],
        ),
    ]
