# Generated by Django 4.2.15 on 2024-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='original_order_id',
            field=models.IntegerField(default='0'),
        ),
    ]
