# Generated by Django 4.2.15 on 2024-11-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_history_original_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='original_order_id',
        ),
    ]
