# Generated by Django 4.2.15 on 2024-11-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_remove_history_original_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='cccd',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='cccd',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
