# Generated by Django 4.2.15 on 2024-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_history_cccd_order_cccd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('seller', 'Chủ Khách Sạn'), ('customer', 'Khách Hàng'), ('admin', 'Người quản lí')], max_length=255),
        ),
    ]
