# Generated by Django 4.2.15 on 2024-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_roomtype_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sus',
            field=models.BooleanField(default=True),
        ),
    ]
