# Generated by Django 4.2.15 on 2024-12-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_room_sus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='sus',
        ),
    ]
