# Generated by Django 4.2.15 on 2024-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room_types',
            field=models.ManyToManyField(blank=True, to='home.roomtype'),
        ),
    ]
