# Generated by Django 4.2.15 on 2024-12-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_producttype_alter_roomtype_name_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cccd',
            field=models.CharField(default='N/a', max_length=255),
        ),
    ]
