# Generated by Django 4.2.15 on 2024-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_alter_userprofile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
