# Generated by Django 4.2.15 on 2024-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_remove_room_status_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
