# Generated by Django 4.2.15 on 2024-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_order_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='method',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
