# Generated by Django 4.2.15 on 2024-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_history_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('seller', 'Chủ Khách Sạn'), ('customer', 'Khách Hàng'), ('admin', 'Người quản lí')], default='customer', max_length=255),
        ),
    ]
