# Generated by Django 4.2.15 on 2024-12-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('seller', 'Chủ CS lưu trú'), ('customer', 'Khách hàng'), ('admin', 'Người quản lí')], default='customer', max_length=255),
        ),
    ]
