# Generated by Django 4.2.15 on 2024-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_userprofile_password_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
