# Generated by Django 4.2.15 on 2024-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='base_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
