# Generated by Django 4.2.15 on 2024-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_userprofile_base_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reset_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
