# Generated by Django 4.2.15 on 2024-12-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_alter_userprofile_reset_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reset_password',
        ),
    ]
