# Generated by Django 4.2.15 on 2024-12-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='static/app/images/default-image.png', null=True, upload_to='rooms/'),
        ),
    ]
