# Generated by Django 4.2.15 on 2024-12-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_alter_new_image_alter_product_imagep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
